# Generated by Django 3.2.9 on 2021-11-13 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20211102_1333'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro',
            fields=[
                ('banhoetosa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='core.banhoetosa')),
                ('animal_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='core.animal')),
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='core.pessoa')),
                ('ID_Cadastro', models.AutoField(primary_key=True, serialize=False)),
            ],
            bases=('core.pessoa', 'core.animal', 'core.banhoetosa'),
        ),
        migrations.AddField(
            model_name='animal',
            name='category_Animal',
            field=models.CharField(choices=[('Pastor Alemao', 'Pastor Alemao'), ('Fila Brasileiro', 'Fila Brasileiro'), ('Pincher', 'Pincher')], default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='animal',
            name='sexo_Animal',
            field=models.CharField(choices=[('MACHO', 'MACHO'), ('FEMEA', 'FEMEA')], default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='animal',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
