# Generated by Django 3.1.7 on 2021-11-25 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20211125_0054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal',
            old_name='RAÇA_Animal',
            new_name='Raça_Animal',
        ),
    ]
